repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: format.go
        name: gofumpt
        entry: gofumpt -w
        language: system
        types: [go]
      - id: imports.go
        name: goimports
        entry: goimports -w .
        language: system
        types: [go]
      - id: lint.go
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
