[tools]
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
pre-commit = "latest"

[tasks.init]
description = "Install hooks and setup environment"
run = "pre-commit install"

[tasks.pre-commit]
description = "Run pre-commit"
run = "pre-commit run --all-files"

[tasks.fmt]
description = "Format Go files"
quiet = true
usage = """
arg "<path>" help="path to run the formatter on"
flag "-w --write" help="Write result to (source) files instead of stdout"
flag "-d --diff"  help="Display diffs instead of rewriting files"
"""
run = """
if [ "$usage_write" = "true" ]; then
  gofumpt -w ${usage_path}
elif [ "$usage_diff" = "true" ]; then
  gofumpt -d ${usage_path}
else
  gofumpt ${usage_path}
fi
"""

[tasks.lint]
description = "Lint Go files"
quiet = true
run = "golangci-lint run"

[hooks]
# Verify all tools defined in [tools] are actually installed
enter = """
tools=$(mise config get tools | cut -d' ' -f1)

missing=""
for tool in $tools; do
  if ! mise which "$tool" > /dev/null 2>&1; then
    missing="$missing $tool"
  fi
done

if [ -n "$missing" ]; then
  echo "\\033[31m[WARNING]\\033[0m"
  echo "Tools defined in mise.toml are not installed:\\033[35m$missing\\033[0m"
  echo "Run '\\033[32mmise install\\033[0m' to set up your environment."
fi
"""
